name: Build and Push Docker Image for Rust

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ vars.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Build and Push Rust Image
        uses: docker/build-push-action@v2
        with:
          context: .  # make sure your Dockerfile for Rust is here
          push: true
          tags: ${{ vars.DOCKER_HUB_USERNAME }}/my_rust_project:${{ github.ref_name }}
